FROM python:3.12

WORKDIR /shop_api

COPY .. /shop_api

RUN python -m pip install --upgrade pip
RUN pip install poetry

RUN poetry install

EXPOSE 80

CMD ["poetry", "run", "uvicorn", "shop_api.main:app", "--host", "0.0.0.0", "--port", "80"]