#Использование облегченного образа
FROM python:3.12-slim

WORKDIR /shop_api

VOLUME /shop_api/data

# Копирование только нужных файлов проекта и зависимостей
COPY pyproject.toml poetry.lock /shop_api/
COPY shop_api /shop_api/shop_api/

# Запись команд через &&, при выполнении создастся только один слой
RUN python -m pip install --upgrade pip && pip install poetry && poetry install

EXPOSE 80

CMD ["poetry", "run", "uvicorn", "shop_api.main:app", "--host", "0.0.0.0", "--port", "80"]